services:
  - type: web
    name: emotional-ticketing
    env: docker
    plan: free
    buildCommand: ./mvnw package -DskipTests
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production